### ISSUE TITLE
Trailing slash in config causes cryptic error

### ISSUE THREAD

**Issue by karl-ehealth** [eHealthAfrica/kazana-bootstrap#10]
took me like half a day to figure out
in my .kazanarc
```
[backend]
  name=couchdb
  location=http://localhost:5984/
```

caused this error
```
[projectname]/node_modules/kazana/bin/server:77
      throw new Error(error.message)
      ^

Error: Name: '_config'. Only lowercase characters (a-z), digits (0-9), and any of the characters _, $, (, ), +, -, and / are allowed. Must begin with a letter.
    at [projectname]/node_modules/kazana/bin/server:77:13
    at [projectname]/node_modules/kazana/node_modules/kazana-server/index.js:137:14
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:697:13
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:52:16
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:267:21
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:44:16
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:694:17
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/async/lib/async.js:173:37
    at [projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/hapi/lib/plugin.js:314:16
    at done ([projectname]/node_modules/kazana/node_modules/kazana-server/node_modules/hapi/node_modules/items/lib/index.js:22:21)
```

would love to help, but i need some pointers, cause this is `require()` all the way down for me. not even sure the error is in this library

**Comment by jo** [comment]
Yes, something is eating the backtrace :(
https://github.com/eHealthAfrica/kazana-server/issues/41

**Comment by jo** [comment]
At least we can allow trailing slashes [here](https://github.com/eHealthAfrica/nano-option) and this will fix this problem for the couchdb-boostrap tools.
